language: go
go_import_path: aqwari.net/xml
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

notifications:
  email:
    recipients: droyo@aqwari.net
    on_success: change
    on_failure: always
