language: go
go_import_path: aqwari.net/xml
go:
  - "1.9"
  - "1.10"
  - "1.11"

install:
  - go get -t -v ./...
  - go get -v golang.org/x/tools/cmd/stringer

before_script:
  - echo "Checking generated files"
  - go generate ./...
  - if [[ -n $(git status -s) ]]; then echo "Unclean working tree"; git diff; exit 1; fi

notifications:
  email:
    recipients: droyo@aqwari.net
    on_success: change
    on_failure: always
